version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MollyElliot21!!!
      POSTGRES_DB: socialbright
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

